// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMIYukgPYU7fbMNu-qhmmyuIGGE6b2fQM',
    appId: '1:330978033723:web:b24742f8e0c75e2fd9dc1e',
    messagingSenderId: '330978033723',
    projectId: 'recipe-and-meal-planner-f276b',
    authDomain: 'recipe-and-meal-planner-f276b.firebaseapp.com',
    storageBucket: 'recipe-and-meal-planner-f276b.firebasestorage.app',
    measurementId: 'G-ZWP4345L3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRJZN8lDXU11fj0ZdP24kae5C94AmBYsM',
    appId: '1:330978033723:android:9f089c5e8f4cf99ed9dc1e',
    messagingSenderId: '330978033723',
    projectId: 'recipe-and-meal-planner-f276b',
    storageBucket: 'recipe-and-meal-planner-f276b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj60OMVTOR3eldMJKPnnhhwwwY06FoG5Q',
    appId: '1:330978033723:ios:3277ec966d8597e9d9dc1e',
    messagingSenderId: '330978033723',
    projectId: 'recipe-and-meal-planner-f276b',
    storageBucket: 'recipe-and-meal-planner-f276b.firebasestorage.app',
    iosBundleId: 'com.example.recipeMealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj60OMVTOR3eldMJKPnnhhwwwY06FoG5Q',
    appId: '1:330978033723:ios:3277ec966d8597e9d9dc1e',
    messagingSenderId: '330978033723',
    projectId: 'recipe-and-meal-planner-f276b',
    storageBucket: 'recipe-and-meal-planner-f276b.firebasestorage.app',
    iosBundleId: 'com.example.recipeMealPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMIYukgPYU7fbMNu-qhmmyuIGGE6b2fQM',
    appId: '1:330978033723:web:096e247e562128bad9dc1e',
    messagingSenderId: '330978033723',
    projectId: 'recipe-and-meal-planner-f276b',
    authDomain: 'recipe-and-meal-planner-f276b.firebaseapp.com',
    storageBucket: 'recipe-and-meal-planner-f276b.firebasestorage.app',
    measurementId: 'G-1T39R04BEJ',
  );
}
